language: swift
osx_image: xcode9.3
xcode_project: ruuvitag-ios.xcodeproject
xcode_scheme: ruuvitag-ios
xcode_sdk: iphonesimulator11.3

env:
    global:
        - WORKSPACE=ruuvitag-ios.xcworkspace
        - SCHEME=ruuvitag-ios
        - DESTINATION="OS=11.3,name=iPhone8"
        - SDK=iphonesimulator

before_install:
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - gem install xcodeproj
    - gem install cocoapods -v '1.4.0'

script:
    - set -o pipefail
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
