language: objective-c
script:
  - xctool -workspace ruuvitag-ios.xcworkspace -scheme ruuvitag-ios -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool run-tests -workspace ruuvitag-ios.xcworkspace -scheme ruuvitag-iosTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
