language: objective-c
xcode_project: ruuvitag-ios.xcodeproj # path to your xcodeproj folder
xcode_scheme: ruuvitag-ios
xcodebuild -workspace ruuvitag-ios.xcworkspace -scheme ruuvitag-ios -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
